# Generated by Django 6.0.6 on 2026-06-30 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('arquivo', models.FileField(upload_to='curriculos/')),
                ('texto_extraido', models.TextField(blank=True)),
                ('skills_extraidas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('skills_exigidas', models.TextField()),
                ('salario_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_encontradas', models.TextField(blank=True)),
                ('skills_faltantes', models.TextField(blank=True)),
                ('percentual_match', models.FloatField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.curriculo')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
        ),
    ]
